# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    
    - script: |
        docker build -t my-container-image-name .
      displayName: 'build Docker image'
    
    - task: SnykSecurityScan@0
      inputs:
        serviceConnectionEndpoint: 'Snyk Pipelines Example Connection'
        testType: 'container'
        dockerImageName: 'my-container-image-name'
        dockerfilePath: 'Dockerfile'
        monitorOnBuild: true
        failOnIssues: true